export class AppConfig {
	
	static authViews = [
		'home','mailerconfigs','modules','appthemes','appconfigs','s3configs','measureunits','materials',
		'accountinggroups','appointmentpages','accountingentrys',
		'simplemails','users','applogs','blogarticles','blogarticlecomments','pagemenus','pagemenuitems',
		'pagemenuitemfiles','images','files','symplaintegrationconfigs','userpaymenttickets',
		'appointmentpageconfigs','conferences','tematicareas','ttematicsubareas','cconferencetematicareas',
		'ccconferencetematicsubareas','coconferencefileconfigs','conconferencists','itaubankconfigs',
		'zabbixreportconfigs','zabbixreports','submissions','s3configappointmentpage',
		'cconconferencistvalidationpoints','iitaubillets','enrollcategorys','sssubmissionevaluators',
		'wconferenceworkevaluationpoints','wsubmissionevaluations',
		//insertionPoint1 -->
	];
	static categories = [
		//insertionPoint2 -->
		['modules',                                ['admin_master']],
	    ['appthemes',                              ['admin_master']],
	    ['appconfigs',                             ['admin_master']],
	    ['s3configs',                              ['admin_master']],
	    ['zabbixreportconfigs',                    ['admin_master']],
	    ['measureunits',                           ['admin_master','admin','system_auditor']],
	    ['materials',                              ['admin_master','admin','system_auditor']],
	    ['accountinggroups',                       ['admin_master','admin','system_auditor']],
	    ['itaubankconfigs',                        ['admin_master','admin','system_auditor']],
	    ['appointmentpages',                       ['admin_master','admin','system_auditor']],
	    ['accountingentrys',                       ['admin_master','admin','system_auditor']],
		['mailerconfigs',                          ['admin_master','admin','system_auditor']],
		['simplemails',                            ['admin_master','admin','system_auditor']],
		['users',                                  ['admin_master','admin','system_auditor']],
		['applogs',                                ['admin_master','admin','system_auditor']],
		['blogarticles',                           ['admin_master','admin','system_auditor']],
		['blogarticlecomments',                    ['admin_master','admin','system_auditor']],
		['pagemenus',                              ['admin_master','admin','system_auditor']],
		['pagemenuitems',                          ['admin_master','admin','system_auditor']],
		['pagemenuitemfiles',                      ['admin_master','admin','system_auditor']],
		['images',                                 ['admin_master','admin','system_auditor']],
		['files',                                  ['admin_master','admin','system_auditor']],
		['symplaintegrationconfigs',               ['admin_master','admin','system_auditor']],
	    ['userpaymenttickets',                     ['admin_master','admin','system_auditor']],
	    ['zabbixreports',                          ['admin_master','admin','system_auditor']],
	    ['appointmentpageconfigs',                 ['admin_master','admin','system_auditor']],
	    ['tematicareas',                           ['admin_master','admin','system_auditor']],
	    ['ttematicsubareas',                       ['admin_master','admin','system_auditor']],
	    ['conferences',                            ['admin_master','admin','system_auditor']],
	    ['cconferencetematicareas',                ['admin_master','admin','system_auditor']],
	    ['ccconferencetematicsubareas',            ['admin_master','admin','system_auditor']],
	    ['coconferencefileconfigs',                ['admin_master','admin','system_auditor']],
	    ['conconferencists',                       ['admin_master','admin','system_auditor']],
	    ['submissions',                            ['admin_master','admin','system_auditor']],
	    ['s3configappointmentpage',                ['admin_master','admin','system_auditor']],
	    ['cconconferencistvalidationpoints',       ['admin_master','admin','system_auditor']],
	    ['iitaubillets',                           ['admin_master','admin','system_auditor']],
	    ['enrollcategorys',                        ['admin_master','admin','system_auditor']],
	    ['sssubmissionevaluators',                 ['admin_master','admin','system_auditor']],
	    ['wconferenceworkevaluationpoints',        ['admin_master','admin','system_auditor']],
	    ['wsubmissionevaluations',                 ['admin_master','admin','system_auditor']],
    ];
	
}